-- 아이디, 비밀번호,이름,이메일, 가입일
CREATE TABLE KH_MEMBER(
MEMBER_ID VARCHAR2(10) PRIMARY KEY,
MEMBER_PW VARCHAR2(20) NOT NULL,
MEMBER_NAME VARCHAR2(15) NOT NULL,
EMAIL VARCHAR2(50),
ENROLL_DATE DATE DEFAULT SYSDATE
);
INSERT INTO KH_MEMBER VALUES
('admin', 1234, '짱구', 'kh01@kh.com', DEFAULT);

INSERT INTO KH_MEMBER VALUES
('user01', 1234, '맹구', 'kh02@kh.com', DEFAULT);

INSERT INTO KH_MEMBER VALUES
('user02', 1234, '철수', 'kh03@kh.com', DEFAULT);

SELECT * FROM KH_MEMBER;




게시글번호,게시글카테고리,작성자,제목,작성일,조회수
;
CREATE SEQUENCE SEQ_KH_BOARD;
DROP TABLE KH_BOARD;
CREATE TABLE KH_BOARD(BOARD_NO NUMBER PRIMARY KEY,
											BOARD_CATEGORY VARCHAR2(20) NOT NULL, 
											BOARD_WRITER VARCHAR2(10) REFERENCES KH_MEMBER, 
											BOARD_TITLE VARCHAR2(300) NOT NULL,
											BOARD_CONTENT VARCHAR2(4000) NOT NULL, 
											COUNT NUMBER DEFAULT 0, 
											CREATE_DATE DATE DEFAULT SYSDATE);

SELECT * FROM KH_BOARD;
