DROP TABLE TB_BOOT_MEMBER;
CREATE TABLE TB_BOOT_MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(20) NOT NULL,
	MEMBER_PW VARCHAR2(64) NOT NULL,
	MEMBER_NAME VARCHAR2(30) NOT NULL,
	TEAM_NO NUMBER NOT NULL,
	MEMBER_ROLE VARCHAR2(15) DEFAULT 'ROLE_USER' NOT NULL,
	CONSTRAINT FK_TEAM FOREIGN KEY (TEAM_NO)
		REFERENCES TB_TEAM_CODE (TEAM_NO)
);


DROP SEQUENCE SEQ_BM;
CREATE SEQUENCE SEQ_BM;

SELECT * FROM TB_BOOT_MEMBER;

SELECT MEMBER_ID, MEMBER_PW, MEMBER_NAME 
FROM TB_BOOT_MEMBER 
WHERE MEMBER_ID = 'hyunwooo';


------------------------------------
CREATE TABLE TB_BOOT_TOKEN (
	TOKEN NVARCHAR2(200) NOT NULL,
	MEMBER_NO NUMBER,
	EXPIRATION NUMBER,
	CONSTRAINT FK_TB_BOOT_TOKEN FOREIGN KEY (MEMBER_NO) REFERENCES TB_BOOT_MEMBER(MEMBER_NO)
);

DROP TABLE TB_BOOT_TOKEN;
SELECT * FROM TB_BOOT_TOKEN;

------------------------------------
CREATE TABLE TB_TEAM_CODE(
	TEAM_NO NUMBER PRIMARY KEY,
	TEAM_NAME VARCHAR2(20) NOT NULL
);

INSERT INTO TB_TEAM_CODE VALUES(1, '두산');
INSERT INTO TB_TEAM_CODE VALUES(2, 'LG');
INSERT INTO TB_TEAM_CODE VALUES(3, '키움');
INSERT INTO TB_TEAM_CODE VALUES(4, '한화');
INSERT INTO TB_TEAM_CODE VALUES(5, 'SSG');
INSERT INTO TB_TEAM_CODE VALUES(6, 'NC');
INSERT INTO TB_TEAM_CODE VALUES(7, '롯데');
INSERT INTO TB_TEAM_CODE VALUES(8, '삼성');
INSERT INTO TB_TEAM_CODE VALUES(9, '기아');
INSERT INTO TB_TEAM_CODE VALUES(10, 'KT');

SELECT * FROM TB_TEAM_CODE;
	
코드 네임값을 리액트로 전달하여 리액트에서 코드이름 출력

-----------------------------------------------
afasdfasfdfa
